version: "3.8"

services:
  frontend:
    build: ./frontend
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - data_frontend:/var/www/app
      - ./frontend/default.conf:/etc/nginx/sites-enabled/default
    environment:
      - VIRTUAL_HOST=faciledaleggere.online,www.faciledaleggere.online
      - LETSENCRYPT_HOST=faciledaleggere.online,www.faciledaleggere.online
      - LETSENCRYPT_EMAIL=admin@bianconiglio.cloud

  backend:
    build: ./backend
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "127.0.0.1:8002:80"
    environment:
      - VIRTUAL_HOST=api.faciledaleggere.online
      - LETSENCRYPT_HOST=api.faciledaleggere.online
    volumes:
      - data_backend:/var/www/app
    env_file:
      - .env.api

  worker:
    build: ./worker
    restart: always
    networks:
      - public_net
      - backend_net
    volumes:
      - data_worker:/var/www/app
    env_file:
      - .env.api

  deploy:
    #build: ./deploy
    image: php:8-apache
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "127.0.0.1:7999:80"
    volumes:
      - data_deploy:/var/www/html
    env_file:
      - .env.deploy

volumes:
  data_frontend:
    external:
      name: flo_frontend
  data_backend:
    external:
      name: flo_backend
  data_worker:
    external:
      name: flo_worker
  data_deploy:
    external:
      name: flo_deploy


networks:
  public_net:
    external:
      name: public_net
  backend_net:

