version: "3.8"

services:

# Web interface        
  frontend:
    build: ./frontend
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - data_frontend:/var/www/app
      - ./frontend/default.conf:/etc/nginx/sites-enabled/default
    environment:
      - VIRTUAL_HOST=faciledaleggere.online,www.faciledaleggere.online
      - LETSENCRYPT_HOST=faciledaleggere.online,www.faciledaleggere.online
      - LETSENCRYPT_EMAIL=admin@bianconiglio.cloud

  backend:
    build: ./backend
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "127.0.0.1:8002:80"
    environment:
      - VIRTUAL_HOST=api.faciledaleggere.online
      - LETSENCRYPT_HOST=api.faciledaleggere.online
    volumes:
      - data_backend:/var/www/app
    env_file:
      - .env.api
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  deploy:
    #build: ./deploy
    image: php:8-apache
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "127.0.0.1:7999:80"
    volumes:
      - data_deploy:/var/www/html
    env_file:
      - .env.deploy

 # Worker

  worker:
    build: ./worker
    restart: always
    networks:
      - backend_net
    volumes:
      - data_worker:/var/www/app
    env_file:
      - .env.api
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  worker-ml:
    build: ./worker-ml
    restart: always
    networks:
      - backend_net
    volumes:
      - data_worker:/var/www/worker
      - data_worker_ml:/var/www/app
      - cache_worker_ml:/root/.cache
    env_file:
      - .env.api
    environment:
      - EMBEDDING_MODEL_NAME=all-MiniLM-L6-v2,sentence-transformers/distiluse-base-multilingual-cased-v2,ArchitRastogi/bert-base-italian-embeddings,nickprock/sentence-bert-base-italian-uncased,GroNLP/gpt2-medium-italian-embeddings,dbmdz/bert-base-italian-xxl-uncased
      - OLLAMA_URL=http://ollama:11434
      - LLM_MODEL=mixtral
    logging:
      driver: "json-file"
      options:
        max-size: "50m"


volumes:
  data_frontend:
    external:
      name: flo_frontend
  data_backend:
    external:
      name: flo_backend
  data_deploy:
    external:
      name: flo_deploy
  data_worker:
    external:
      name: flo_worker
  data_worker_ml:
    external:
      name: flo_worker-ml
  cache_worker_ml:
    external:
      name: flo_worker-ml_cache

networks:
  public_net:
    external:
      name: public_net
  backend_net:

