version: "3.8"

services:
  frontend:
    build: ./frontend
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "8001:80"
    volumes:
      - data_frontend:/var/www/app
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    #environment:
    #  - VIRTUAL_HOST=bianconiglio.cloud
    #  - LETSENCRYPT_HOST=bianconiglio.cloud
    #  - LETSENCRYPT_EMAIL=admin@bianconiglio.cloud

  backend:
    build: ./backend
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "8002:80"
    volumes:
      - data_backend:/var/www/app

  deploy:
    build: ./deploy
    restart: always
    networks:
      - public_net
      - backend_net
    ports:
      - "7999:80"
    #environment:
    #  - VIRTUAL_HOST=bianconiglio.cloud

volumes:
  data_frontend:
    external:
      name: flo_frontend
  data_backend:
    external:
      name: flo_backend


networks:
  public_net:
    external:
      name: public_net
  backend_net:
